/* ============================================================
   GreenKart — product catalogue, categories, journal posts.
   Categories: health, beauty, hygiene, food.
   ============================================================ */

window.PRODUCTS = [
  /* ========== HEALTH & STRENGTH ========== */
  { id: 1, slug: 'marine-collagen-powder',
    cat: 'health', subcat: 'Collagen',
    title: 'Marine Collagen Powder',
    subtitle: 'Hydrolysed peptides, unflavoured',
    price: 42.00, old: 48.00, weight: '200 g pouch',
    origin: 'Wild-caught, Iceland',
    farmer: 'Kalda Naturals',
    farmerSince: 'since 2009',
    farmerQuote: 'Nothing is wasted — every fish becomes food, feed or collagen.',
    tags: ['Hydrolysed', 'Single source', 'No fillers'],
    img: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=1200&q=85&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=1200&q=85&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=1200&q=85&auto=format&fit=crop',
    ],
    description: 'Pure hydrolysed marine collagen from sustainably caught Icelandic cod. Dissolves clear in hot or cold liquids. Unflavoured.',
    story: 'Kalda Naturals operates a closed-loop cooperative that uses every part of the catch — collagen is extracted from skin and bone that would otherwise be waste. Independently tested for heavy metals on every batch.',
    keeps: '24 months, sealed · 3 months once opened',
    stock: 28, rating: 4.8, reviews: 192,
    featured: true, season: 'all' },

  { id: 2, slug: 'omega-3-fish-oil',
    cat: 'health', subcat: 'Omega-3',
    title: 'Omega-3 Fish Oil',
    subtitle: '60 softgels · 1000 mg',
    price: 24.50, old: null, weight: '60 softgels',
    origin: 'Pacific, USA',
    farmer: 'Nord Sea Labs',
    farmerSince: 'since 2003',
    farmerQuote: 'Our oil is bottled within ten days of catch.',
    tags: ['Molecularly distilled', 'Third-party tested'],
    img: 'https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?w=1200&q=85&auto=format&fit=crop',
    description: 'High-concentration EPA/DHA fish oil from small-vessel wild catch. Low-temperature distilled to remove heavy metals.',
    story: 'Nord Sea Labs purchase only from vessels under 60 ft, all of which land their catch the day it is pulled.',
    keeps: '24 months, cool and dark',
    stock: 54, rating: 4.7, reviews: 311,
    featured: false, season: 'all' },

  { id: 3, slug: 'l-tryptophan-capsules',
    cat: 'health', subcat: 'Amino acids',
    title: 'L-Tryptophan Capsules',
    subtitle: '500 mg · 30 vegan capsules',
    price: 37.60, old: null, weight: '30 capsules',
    origin: 'Fermented, Germany',
    farmer: 'Freiburg Ferments',
    farmerSince: 'since 2015',
    farmerQuote: 'Amino acids from fermentation, never from feathers.',
    tags: ['Plant fermented', 'Vegan'],
    img: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=1200&q=85&auto=format&fit=crop',
    description: 'A plant-fermented form of tryptophan, the amino acid that supports restful sleep and balanced mood.',
    story: 'Freiburg Ferments grows its strains on molasses and plant sugars — no animal-derived feedstocks.',
    keeps: '24 months, sealed',
    stock: 36, rating: 4.5, reviews: 88,
    featured: false, season: 'all' },

  { id: 4, slug: 'herbal-red-clover-tincture',
    cat: 'health', subcat: 'Tinctures',
    title: 'Red Clover Herbal Tincture',
    subtitle: 'Traditional support for circulation',
    price: 8.80, old: null, weight: '50 ml dropper',
    origin: 'Vermont',
    farmer: 'Windy Hill Apothecary',
    farmerSince: 'since 1994',
    farmerQuote: 'We wild-harvest on a thirteen-year rotation. The meadow takes its rest.',
    tags: ['Wild harvested', 'Hand pressed'],
    img: 'https://images.unsplash.com/photo-1611073615452-4889ae4664bd?w=1200&q=85&auto=format&fit=crop',
    description: 'Traditional red clover tincture made with wild-harvested blossoms and grain alcohol, hand-pressed in small batches.',
    story: 'Windy Hill works a four-acre meadow on a long rotation to let each patch rest and return.',
    keeps: '36 months, sealed',
    stock: 22, rating: 4.8, reviews: 46,
    featured: true, season: 'all' },

  { id: 5, slug: 'bach-flower-drops-quit',
    cat: 'health', subcat: 'Flower essences',
    title: 'Bach Flower Drops — Quit Support',
    subtitle: 'Traditional five-flower formula',
    price: 13.00, old: null, weight: '20 ml dropper',
    origin: 'Made in USA',
    farmer: 'Stillwater Essences',
    farmerSince: 'since 2001',
    farmerQuote: 'Old practice, quietly done.',
    tags: ['Traditional'],
    img: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=1200&q=85&auto=format&fit=crop',
    description: 'A five-flower Bach formula traditionally recommended to support the emotional side of breaking a habit.',
    story: 'Stillwater prepares essences in glass on spring water, following the traditional Dr Bach method.',
    keeps: '24 months',
    stock: 14, rating: 4.6, reviews: 72,
    featured: false, season: 'all' },

  { id: 6, slug: 'gelatin-grass-fed',
    cat: 'health', subcat: 'Collagen',
    title: 'Grass-fed Beef Gelatin',
    subtitle: 'Unflavoured · for broths & jellies',
    price: 17.80, old: null, weight: '400 g',
    origin: 'Pasture-raised, Brazil',
    farmer: 'Cooperativa Verde',
    farmerSince: 'since 1998',
    farmerQuote: 'Grass, sun, and time.',
    tags: ['Grass-fed', 'Pasture-raised'],
    img: 'https://images.unsplash.com/photo-1607602132700-068258431c6c?w=1200&q=85&auto=format&fit=crop',
    description: 'Unflavoured grass-fed beef gelatin for broths, jellies, gummies, or adding to a morning cup.',
    story: 'Cooperativa Verde is a collective of eight family farms working rotational pasture in the Cerrado.',
    keeps: '36 months, sealed',
    stock: 44, rating: 4.7, reviews: 158,
    featured: false, season: 'all' },

  /* ========== BEAUTY & WELLNESS ========== */
  { id: 10, slug: 'lavender-essential-oil',
    cat: 'beauty', subcat: 'Essential oils',
    title: 'Lavender Essential Oil',
    subtitle: 'Steam-distilled, Provence',
    price: 5.95, old: null, weight: '10 ml',
    origin: 'Provence, France',
    farmer: 'Maison de la Lavande',
    farmerSince: 'since 1972',
    farmerQuote: 'The mountain lavender is a different plant, different oil.',
    tags: ['Steam-distilled', 'Single origin'],
    img: 'https://images.unsplash.com/photo-1595392029731-a6a402bb536d?w=1200&q=85&auto=format&fit=crop',
    description: 'Single-origin lavender essential oil from a seven-hundred-metre Provençal plateau. Sweet, floral, calming.',
    story: 'Maison de la Lavande keeps its own fields above the tree line — the altitude concentrates the linalool.',
    keeps: '24 months, cool and dark',
    stock: 62, rating: 4.9, reviews: 264,
    featured: true, season: 'all' },

  { id: 11, slug: 'rose-water-toner',
    cat: 'beauty', subcat: 'Facial care',
    title: 'Rose Water Toner',
    subtitle: 'Damask rose, hand-distilled',
    price: 12.40, old: null, weight: '250 ml glass',
    origin: 'Isparta, Türkiye',
    farmer: 'Gül Kooperatifi',
    farmerSince: 'since 1961',
    farmerQuote: 'We distil at dawn. That is when the rose gives its best water.',
    tags: ['Hand-distilled', 'Single ingredient'],
    img: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1200&q=85&auto=format&fit=crop',
    description: 'A simple, single-ingredient rose water from Damask blooms hand-distilled at dawn in small copper alembics.',
    story: 'The cooperative pools the harvest from thirty family gardens and distils it within four hours of picking.',
    keeps: '18 months, refrigerated once opened',
    stock: 38, rating: 4.8, reviews: 172,
    featured: false, season: 'all' },

  { id: 12, slug: 'argan-shampoo-bar',
    cat: 'beauty', subcat: 'Hair',
    title: 'Argan Oil Shampoo Bar',
    subtitle: 'Plastic-free · cold-process',
    price: 9.80, old: null, weight: '95 g bar',
    origin: 'Made in USA',
    farmer: 'Maple Lane Soap Co.',
    farmerSince: 'since 2016',
    farmerQuote: 'One bar replaces three plastic bottles, roughly.',
    tags: ['Plastic-free', 'Cold-processed'],
    img: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=1200&q=85&auto=format&fit=crop',
    description: 'A cold-process shampoo bar with fair-trade argan oil and a whisper of rosemary. No sulphates, no plastic.',
    story: 'Poured by hand in small batches and cured for six weeks before it leaves the shelf.',
    keeps: '36 months, dry',
    stock: 70, rating: 4.7, reviews: 144,
    featured: false, season: 'all' },

  { id: 13, slug: 'herbal-hair-dye-light-brown',
    cat: 'beauty', subcat: 'Hair',
    title: 'Herbal Hair Dye — Light Brown',
    subtitle: 'Henna, cassia, indigo',
    price: 7.00, old: null, weight: '70 g',
    origin: 'Made in Germany',
    farmer: 'Kräuter Haus',
    farmerSince: 'since 1989',
    farmerQuote: 'Three plants, nothing else.',
    tags: ['Plant-only', 'PPD-free'],
    img: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=1200&q=85&auto=format&fit=crop',
    description: 'A three-herb blend that deposits warm, natural-looking colour without harsh chemicals or PPD.',
    story: 'The formula hasn\'t changed since 1989 — and neither has the line of regulars buying it.',
    keeps: '36 months, sealed',
    stock: 32, rating: 4.5, reviews: 61,
    featured: false, season: 'all' },

  { id: 14, slug: 'bio-day-cream',
    cat: 'beauty', subcat: 'Facial care',
    title: 'Rosehip Day Cream',
    subtitle: 'For dry and sensitive skin',
    price: 28.00, old: 34.00, weight: '50 ml glass',
    origin: 'Made in USA',
    farmer: 'Still Studio',
    farmerSince: 'since 2019',
    farmerQuote: 'Six ingredients, each doing real work.',
    tags: ['Six ingredients', 'Fragrance-free'],
    img: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=1200&q=85&auto=format&fit=crop',
    description: 'A minimalist day cream built on rosehip seed oil and squalane. Six ingredients, fragrance-free.',
    story: 'Still Studio tests short — every formula lists its ingredients and the reason each one is there.',
    keeps: '12 months, once opened',
    stock: 18, rating: 4.9, reviews: 88,
    featured: true, season: 'all' },

  /* ========== HOME & HYGIENE ========== */
  { id: 20, slug: 'deodorizing-foot-powder',
    cat: 'hygiene', subcat: 'Foot care',
    title: 'Deodorising Foot Powder',
    subtitle: 'Zinc + clay + peppermint',
    price: 4.40, old: null, weight: '75 g',
    origin: 'Made in USA',
    farmer: 'Bright Ledge Apothecary',
    farmerSince: 'since 2012',
    farmerQuote: 'Simple things done well.',
    tags: ['Aluminum-free'],
    img: 'https://images.unsplash.com/photo-1620916297893-4c1a02826f9f?w=1200&q=85&auto=format&fit=crop',
    description: 'A simple zinc-and-clay powder with a clean peppermint finish. Works.',
    story: 'Based on a 1950s formula the founder found in a relative\'s store and kept.',
    keeps: '36 months',
    stock: 90, rating: 4.7, reviews: 214,
    featured: false, season: 'all' },

  { id: 21, slug: 'bamboo-toothbrush-pack',
    cat: 'hygiene', subcat: 'Oral care',
    title: 'Bamboo Toothbrush',
    subtitle: 'Pack of four · soft bristles',
    price: 11.20, old: null, weight: 'Pack of 4',
    origin: 'Made in Vietnam',
    farmer: 'Mekong Bamboo Co-op',
    farmerSince: 'since 2014',
    farmerQuote: 'Our bamboo renews in five years, not fifty.',
    tags: ['Compostable handle', 'Recyclable packaging'],
    img: 'https://images.unsplash.com/photo-1603729362753-f8162ac6c3df?w=1200&q=85&auto=format&fit=crop',
    description: 'A set of four soft-bristle bamboo brushes with compostable handles and recyclable paperboard packaging.',
    story: 'The cooperative grows its bamboo on non-arable land and rotates harvest annually.',
    keeps: 'Replace every 3 months',
    stock: 128, rating: 4.6, reviews: 186,
    featured: false, season: 'all' },

  { id: 22, slug: 'natural-hand-soap',
    cat: 'hygiene', subcat: 'Bath',
    title: 'Natural Hand Soap',
    subtitle: 'Olive + laurel · castile base',
    price: 7.60, old: null, weight: '500 ml glass',
    origin: 'Made in Greece',
    farmer: 'Evia Soap Works',
    farmerSince: 'since 1987',
    farmerQuote: 'If it isn\'t simple, we don\'t sell it.',
    tags: ['Plant-based', 'Refillable bottle'],
    img: 'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=1200&q=85&auto=format&fit=crop',
    description: 'A traditional olive-and-laurel castile liquid soap in a refillable glass bottle.',
    story: 'Made from oil pressed within twenty miles of the workshop and laurel gathered on the island.',
    keeps: '24 months',
    stock: 54, rating: 4.8, reviews: 98,
    featured: true, season: 'all' },

  { id: 23, slug: 'mineral-deodorant-stick',
    cat: 'hygiene', subcat: 'Deodorant',
    title: 'Mineral Deodorant Stick',
    subtitle: 'Aluminum-free · 48 hour',
    price: 9.00, old: 11.50, weight: '70 g stick',
    origin: 'Made in USA',
    farmer: 'Bright Ledge Apothecary',
    farmerSince: 'since 2012',
    farmerQuote: 'We wear it ourselves, all summer.',
    tags: ['Aluminium-free', 'Unscented variant'],
    img: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=1200&q=85&auto=format&fit=crop',
    description: 'A twist-up mineral deodorant built on magnesium hydroxide. Effective without aluminium salts.',
    story: 'Tested for two summers by the founder\'s extended family before the product launched.',
    keeps: '24 months',
    stock: 46, rating: 4.6, reviews: 132,
    featured: false, season: 'all' },

  /* ========== FOOD & DRINKS ========== */
  { id: 30, slug: 'raw-wildflower-honey',
    cat: 'food', subcat: 'Honey',
    title: 'Raw Wildflower Honey',
    subtitle: 'Unfiltered · hand-extracted',
    price: 14.50, old: null, weight: '500 g jar',
    origin: 'Northern Vermont',
    farmer: 'Gibson Apiary',
    farmerSince: 'since 2003',
    farmerQuote: 'Every jar tastes of wherever the bees were that week.',
    tags: ['Raw', 'Single origin'],
    img: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200&q=85&auto=format&fit=crop',
    description: 'Unfiltered, unpasteurised wildflower honey from a small northern Vermont apiary. Crystallises after a month — warm gently.',
    story: 'Bill Gibson keeps forty hives on a buckwheat meadow. He extracts a few dozen jars at a time, by hand.',
    keeps: 'Indefinitely, sealed',
    stock: 40, rating: 4.9, reviews: 156,
    featured: true, season: 'all' },

  { id: 31, slug: 'ceremonial-matcha',
    cat: 'food', subcat: 'Tea',
    title: 'Ceremonial-grade Matcha',
    subtitle: 'First harvest · stone-ground',
    price: 28.00, old: 34.00, weight: '40 g tin',
    origin: 'Uji, Japan',
    farmer: 'Marufuku Tea Fields',
    farmerSince: 'since 1871',
    farmerQuote: 'The first harvest of spring — nothing else will do for tea.',
    tags: ['First harvest', 'Stone-ground'],
    img: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=1200&q=85&auto=format&fit=crop',
    description: 'A ceremonial-grade matcha from a seventh-generation family field in Uji. Bright, vegetal, almost sweet.',
    story: 'Shade-grown for three weeks, hand-picked, steamed, dried, and stone-ground at eighty revolutions a minute.',
    keeps: '6 months, refrigerated once opened',
    stock: 18, rating: 4.9, reviews: 78,
    featured: true, season: 'all' },

  { id: 32, slug: 'cold-pressed-olive-oil',
    cat: 'food', subcat: 'Oils',
    title: 'Cold-pressed Olive Oil',
    subtitle: 'Single-estate Tuscan',
    price: 24.00, old: null, weight: '500 ml tin',
    origin: 'Toscana, Italy',
    farmer: 'Podere Vecchio',
    farmerSince: 'since 1962',
    farmerQuote: 'The mill runs four hours a day in November. That\'s our season.',
    tags: ['Single estate', 'Cold pressed'],
    img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1200&q=85&auto=format&fit=crop',
    description: 'A single-estate Tuscan olive oil, cold-pressed within four hours of picking. Peppery, green, and alive.',
    story: 'Podere Vecchio presses only one hundred tins a year. We take half of them.',
    keeps: '18 months, cool and dark',
    stock: 28, rating: 4.8, reviews: 92,
    featured: true, season: 'all' },

  { id: 33, slug: 'bio-chlorella-powder',
    cat: 'food', subcat: 'Superfoods',
    title: 'Bio Chlorella Powder',
    subtitle: 'Single-strain · cracked cell',
    price: 19.90, old: null, weight: '150 g jar',
    origin: 'Cultivated, Taiwan',
    farmer: 'Clear Lake Algae',
    farmerSince: 'since 1998',
    farmerQuote: 'We grow it in daylight and spring water — that is all.',
    tags: ['Cracked-cell', 'Spring-water grown'],
    img: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=85&auto=format&fit=crop',
    description: 'A single-strain chlorella powder with a mechanically cracked cell wall for better absorption.',
    story: 'Grown in outdoor tanks fed by an on-site spring — no synthetic nitrogen, no CO₂ injection.',
    keeps: '18 months',
    stock: 34, rating: 4.6, reviews: 65,
    featured: false, season: 'all' },

  { id: 34, slug: 'granola-nuts-berries',
    cat: 'food', subcat: 'Breakfast',
    title: 'Granola with Nuts & Berries',
    subtitle: 'Oven-baked · low sugar',
    price: 8.40, old: null, weight: '350 g bag',
    origin: 'Burlington, Vermont',
    farmer: 'GreenKart Kitchen',
    farmerSince: 'since 2024',
    farmerQuote: 'Oats, maple, patience. Same as the bread.',
    tags: ['Small-batch', 'Low-sugar'],
    img: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1200&q=85&auto=format&fit=crop',
    description: 'Our own house granola — rolled oats, Vermont maple, pecans, dried blueberries, and a pinch of sea salt.',
    story: 'Baked in our small kitchen three mornings a week.',
    keeps: '6 weeks, sealed',
    stock: 60, rating: 4.7, reviews: 58,
    featured: false, season: 'all' },

  { id: 35, slug: 'organic-almonds',
    cat: 'food', subcat: 'Nuts',
    title: 'Organic Raw Almonds',
    subtitle: 'Single-orchard, California',
    price: 11.60, old: null, weight: '300 g bag',
    origin: 'Capay Valley, California',
    farmer: 'Capay Organic',
    farmerSince: 'since 1989',
    farmerQuote: 'Almonds are a desert crop. Drip-irrigated and honest.',
    tags: ['Certified organic', 'Single orchard'],
    img: 'https://images.unsplash.com/photo-1574493582880-36b22d2c1ef2?w=1200&q=85&auto=format&fit=crop',
    description: 'Unpasteurised raw almonds from a single orchard in the Capay Valley. Sweet, milky, and worth the wait.',
    story: 'Harvested in September and shipped direct to us. Nothing sits in a warehouse.',
    keeps: '3 months, cool',
    stock: 44, rating: 4.6, reviews: 42,
    featured: false, season: 'autumn' },

  { id: 36, slug: 'turmeric-ginger-tea',
    cat: 'food', subcat: 'Tea',
    title: 'Turmeric & Ginger Tea',
    subtitle: 'Loose-leaf · warming blend',
    price: 12.80, old: null, weight: '80 g tin',
    origin: 'Blended in USA',
    farmer: 'Small Ritual Tea',
    farmerSince: 'since 2017',
    farmerQuote: 'Warming, peppery, and bright. A good morning cup.',
    tags: ['Hand-blended', 'Caffeine-free'],
    img: 'https://images.unsplash.com/photo-1597317613208-b44e41f83eaa?w=1200&q=85&auto=format&fit=crop',
    description: 'A warming loose-leaf blend of turmeric, ginger, black pepper, and lemongrass. Caffeine-free.',
    story: 'Blended weekly in small glass jars so the oils stay bright.',
    keeps: '12 months, sealed',
    stock: 48, rating: 4.7, reviews: 94,
    featured: false, season: 'all' },
];

window.CATEGORIES = [
  { key: 'all',     label: 'Everything',     tint: '#4f8528', icon: 'layers' },
  { key: 'health',  label: 'Health',         tint: '#4f8528', icon: 'heart' },
  { key: 'beauty',  label: 'Beauty',         tint: '#b75b89', icon: 'leaf' },
  { key: 'hygiene', label: 'Hygiene',        tint: '#2886b5', icon: 'drop' },
  { key: 'food',    label: 'Food & Drinks',  tint: '#4f8528', icon: 'sprout' },
];

window.JOURNAL = [
  { id: 'p1', slug: 'collagen-vs-gelatin',
    title: 'Gelatin vs hydrolysed collagen — what\'s the real difference?',
    excerpt: 'Both come from the same source. The distinction is how much processing you need for your body to actually absorb it.',
    date: '2026-04-12', read: 6, author: 'Naomi Hart', category: 'Wellness',
    img: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=1600&q=90&auto=format&fit=crop',
    body: [
      'Gelatin and hydrolysed collagen begin in the same place — animal connective tissue — and end up looking like two quite different products on a shelf. What separates them is a processing step called hydrolysis.',
      'Gelatin is collagen that has been partially broken down by heat and acid. It sets to a jelly when cool, which is why it\'s used for broths, gummies, and traditional jellies.',
      'Hydrolysed collagen takes that same material and breaks it down further into short peptide chains. It no longer gels — but those shorter chains are easier for the body to absorb.',
      'The practical takeaway: pick gelatin for cooking (where you want the setting behaviour), and hydrolysed collagen for something you plan to stir into water or coffee and drink.',
    ] },
  { id: 'p2', slug: 'cellulite-myths',
    title: 'Five cellulite myths, quietly disproved.',
    excerpt: 'Summer approaches, so do the promises. Most are nonsense; a few habits genuinely help. Here\'s what evidence actually supports.',
    date: '2026-04-05', read: 7, author: 'Kim Okorocha', category: 'Body',
    img: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1600&q=90&auto=format&fit=crop',
    body: [
      'Cellulite is structural — a texture of the skin caused by how connective tissue tethers to fat beneath. It is not a toxin, a diet, or a moral failing.',
      'Myth one: you can cream it away. Creams change surface moisture at most. Myth two: cardio alone fixes it. Evidence is thin. Myth three: juice cleanses help. No.',
      'What genuinely helps is a boring triad — resistance training for muscle tone, steady hydration, and time. That\'s less marketable, which is why you rarely see it on a label.',
    ] },
  { id: 'p3', slug: 'essential-oils-how-to-read-a-label',
    title: 'How to read an essential-oil label.',
    excerpt: 'Steam-distilled, absolute, CO₂-extracted — the extraction method matters more than the marketing copy. A short field guide.',
    date: '2026-03-28', read: 5, author: 'Paul Mensah', category: 'Beauty',
    img: 'https://images.unsplash.com/photo-1595392029731-a6a402bb536d?w=1600&q=90&auto=format&fit=crop',
    body: [
      'Most essential oils are made in one of three ways: steam distillation, solvent-and-wash extraction (producing an "absolute"), or CO₂ extraction.',
      'Steam distillation gives a classic essential oil — what people think of when they hear the term. Absolutes are richer, but carry a trace of the solvent. CO₂ extracts capture heat-sensitive notes without heat or solvent.',
      'A good label will also print origin (country and region), the Latin name of the plant, the part used, and the year of harvest. If it prints none of those, assume the oil is a blend bought on a commodity market.',
    ] },
  { id: 'p4', slug: 'plastic-free-bathroom',
    title: 'Swapping a plastic-free bathroom, one habit at a time.',
    excerpt: 'A six-week plan to replace daily plastics without throwing anything usable out. Realistic, not preachy.',
    date: '2026-03-20', read: 4, author: 'Lila Song', category: 'Sustainability',
    img: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=1600&q=90&auto=format&fit=crop',
    body: [
      'Starting over is expensive and wasteful. A better tactic is to replace items only as the old ones run out — and to start with the shortest-lived products first.',
      'Week one: toothbrush. Week two: shampoo. Week three: soap. By week six you\'ll have swapped five or six single-use plastics for long-lived alternatives, without a single thrown-out tube.',
      'The point is not purity. It is reducing how often you buy, rebuy, and discard.',
    ] },
];

window.FARMS = [
  { id: 'f1', name: 'Kalda Naturals', location: 'Iceland',
    since: 2009, acres: 0, specialty: 'Marine collagen, cod-oil derivatives',
    img: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=1400&q=90&auto=format&fit=crop',
    text: 'A closed-loop cooperative using every part of a sustainably caught Icelandic cod.' },
  { id: 'f2', name: 'Gibson Apiary', location: 'Northern Vermont',
    since: 2003, acres: 6, specialty: 'Raw wildflower honey',
    img: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1400&q=90&auto=format&fit=crop',
    text: 'Forty hives in a buckwheat meadow. Honey extracted by hand, a few dozen jars at a time.' },
  { id: 'f3', name: 'Maison de la Lavande', location: 'Provence, France',
    since: 1972, acres: 34, specialty: 'High-altitude lavender essential oil',
    img: 'https://images.unsplash.com/photo-1595392029731-a6a402bb536d?w=1400&q=90&auto=format&fit=crop',
    text: 'Mountain lavender distilled at dawn. Forty-three years of the same family doing the same work.' },
  { id: 'f4', name: 'Marufuku Tea Fields', location: 'Uji, Japan',
    since: 1871, acres: 12, specialty: 'Ceremonial-grade matcha',
    img: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=1400&q=90&auto=format&fit=crop',
    text: 'Seven generations, one hillside, one kind of tea — shaded and stone-ground the slow way.' },
  { id: 'f5', name: 'Podere Vecchio', location: 'Toscana, Italy',
    since: 1962, acres: 18, specialty: 'Single-estate olive oil',
    img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1400&q=90&auto=format&fit=crop',
    text: 'A four-hour-a-day mill running only in November. One hundred tins a year.' },
  { id: 'f6', name: 'Mekong Bamboo Co-op', location: 'Vietnam',
    since: 2014, acres: 80, specialty: 'Bamboo goods, compostable packaging',
    img: 'https://images.unsplash.com/photo-1603729362753-f8162ac6c3df?w=1400&q=90&auto=format&fit=crop',
    text: 'Working bamboo on non-arable land, rotating harvest annually. Replaces the plastics that matter.' },
];
