/* ============================================================
   GreenKart — product catalogue, categories, journal posts.
   Loaded before script.js on every page.
   ============================================================ */

window.PRODUCTS = [
  {
    id: 1, slug: 'wild-hillside-blueberries',
    cat: 'fruits', subcat: 'Berries',
    title: 'Wild Hillside Blueberries',
    subtitle: 'Uncultivated clone, Hardwick Ridge',
    price: 6.25, old: 8.00, weight: '125 g punnet',
    origin: 'Hardwick, Vermont',
    farmer: 'The Abernathy Family',
    farmerSince: 'since 1978',
    farmerQuote: 'We pick before the birds find them — that\'s the whole secret.',
    tags: ['Wild-harvested', 'Certified organic', 'Fair wage'],
    img: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=1600&q=90&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=1600&q=90&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=1600&q=90&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=1600&q=90&auto=format&fit=crop',
    ],
    description: 'Small, dark, and acid — the way a berry is supposed to taste before breeding made them sweet. Hand-picked from a wild hillside clone by the Abernathy family. Pairs with stone fruit, lemon thyme, and an old-fashioned.',
    story: 'Picked by the Abernathy family before the birds find them, these berries are smaller, darker, and more acid than their supermarket cousins. They stain linen generously and pair with stone fruit, lemon thyme, and an old-fashioned. We sold out last season in nine days.',
    keeps: '≤ 6 days, chilled',
    stock: 9, rating: 4.9, reviews: 312,
    featured: true, season: 'spring',
  },
  {
    id: 2, slug: 'brandywine-tomatoes',
    cat: 'vegetables', subcat: 'Heirloom',
    title: 'Heirloom Brandywine Tomatoes',
    subtitle: 'Pink-shouldered, ninety-day strain',
    price: 4.49, old: 6.00, weight: '500 g (≈ 3 tomatoes)',
    origin: 'Sonoma County, California',
    farmer: 'Ortega Family Farm',
    farmerSince: 'since 1953',
    farmerQuote: 'We harvest on the morning the sky tells us to. The calendar is a suggestion; the weather is the boss.',
    tags: ['Certified organic', 'Heirloom'],
    img: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=1600&q=90&auto=format&fit=crop',
    description: 'A pink-shouldered heirloom with shoulders that crack and juice that stains. Perfect for slicing, salting, and eating standing at the counter.',
    story: 'The Ortegas have grown Brandywines since 1953 on soil their grandfather first turned over with a horse. Every August the greenhouse gives up a few hundred pounds of these sun-shouldered fruits, grown exactly the way they always have been.',
    keeps: '≤ 5 days, cool pantry',
    stock: 24, rating: 4.8, reviews: 201,
    featured: false, season: 'summer',
  },
  {
    id: 3, slug: 'country-sourdough',
    cat: 'bakery', subcat: 'Bread',
    title: 'Country Sourdough Loaf',
    subtitle: 'Stone-milled, 36-hour cold ferment',
    price: 7.50, old: null, weight: '800 g',
    origin: 'Brooklyn, New York',
    farmer: 'Mill Street Bakery',
    farmerSince: 'since 2018',
    farmerQuote: 'A loaf should crackle when you tear it. Ours does.',
    tags: ['Hand-shaped', 'Stone-milled flour'],
    img: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=1600&q=90&auto=format&fit=crop',
    description: 'Stone-milled flour, a thirty-six-hour cold ferment, and a dark-roasted crust. Keeps a week on the counter if you cut the face down.',
    story: 'Baked on Thursdays in a small basement in Brooklyn. Each loaf is hand-shaped, retarded overnight, and baked in a deck oven at 260°C. Sweet, mild crumb with a crackle crust.',
    keeps: '7 days, cut-side down',
    stock: 12, rating: 4.9, reviews: 412,
    featured: true, season: 'all',
  },
  {
    id: 4, slug: 'fuji-apples',
    cat: 'fruits', subcat: 'Orchard',
    title: 'Fuji Apples',
    subtitle: 'Crisp, sweet, late-season',
    price: 3.10, old: 4.40, weight: '6 pieces',
    origin: 'Hood River, Oregon',
    farmer: 'The Ortega Valley Orchard',
    farmerSince: 'since 1982',
    farmerQuote: 'You can\'t rush an apple. Only wait it out.',
    tags: ['Certified organic'],
    img: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=1600&q=90&auto=format&fit=crop',
    description: 'Late-season Fujis from a high-altitude Oregon orchard. Dense, crisp, and just sweet enough — they keep in the cellar through March.',
    story: 'Grown at 2,200 feet in the Hood River Valley. The cold nights in October push the sugar and tighten the flesh.',
    keeps: '3 weeks, chilled',
    stock: 48, rating: 4.6, reviews: 144,
    featured: false, season: 'autumn',
  },
  {
    id: 5, slug: 'grass-fed-whole-milk',
    cat: 'dairy', subcat: 'Milk',
    title: 'Grass-fed Whole Milk',
    subtitle: 'Non-homogenised, in reusable glass',
    price: 3.95, old: null, weight: '1 L glass bottle',
    origin: 'Middlebury, Vermont',
    farmer: 'Green Pastures Dairy',
    farmerSince: 'since 1964',
    farmerQuote: 'You can taste what the cows ate last Tuesday.',
    tags: ['Grass-fed', 'Non-homogenised', 'Returnable bottle'],
    img: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=1600&q=90&auto=format&fit=crop',
    description: 'Non-homogenised whole milk from a single small herd. Comes in a returnable glass bottle — $1 deposit refunded on return.',
    story: 'Green Pastures milks forty-eight Jersey cows twice a day. The milk is bottled the same morning in a converted barn.',
    keeps: '10 days, refrigerated',
    stock: 36, rating: 4.7, reviews: 89,
    featured: false, season: 'all',
  },
  {
    id: 6, slug: 'hass-avocados',
    cat: 'vegetables', subcat: 'Pantry',
    title: 'Hass Avocados',
    subtitle: 'Ready Thursday',
    price: 6.00, old: null, weight: 'Pack of 4',
    origin: 'Michoacán, Mexico',
    farmer: 'Cooperativa San Juan',
    farmerSince: 'since 1998',
    farmerQuote: 'We don\'t pick green — we wait.',
    tags: ['Fair trade', 'Tree-ripened'],
    img: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=1600&q=90&auto=format&fit=crop',
    description: 'Tree-ripened Hass avocados from a small fair-trade cooperative. Sold when they\'re ready to eat Thursday — not when they\'re picked.',
    story: 'Cooperativa San Juan waits until each fruit passes a density test before picking. Nothing is gassed, nothing is cold-stored.',
    keeps: '4 days once ripe',
    stock: 22, rating: 4.5, reviews: 98,
    featured: false, season: 'all',
  },
  {
    id: 7, slug: 'brown-hen-eggs',
    cat: 'dairy', subcat: 'Eggs',
    title: 'Brown Hen Eggs',
    subtitle: 'Pastured, dozen, gathered yesterday',
    price: 5.20, old: null, weight: '12 count',
    origin: 'Lancaster County, Pennsylvania',
    farmer: 'Stoltz Family Poultry',
    farmerSince: 'since 1971',
    farmerQuote: 'Grass-fed, sun-fed, never-rushed.',
    tags: ['Pastured', 'Soy-free feed'],
    img: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=1600&q=90&auto=format&fit=crop',
    description: 'Pastured brown eggs from a family farm that\'s been doing it the same way since 1971. Yolks the color of sunset.',
    story: 'The Stoltzes keep three hundred hens on rotating pasture. The eggs arrive the morning after they\'re laid.',
    keeps: '4 weeks, chilled',
    stock: 54, rating: 4.8, reviews: 267,
    featured: true, season: 'all',
  },
  {
    id: 8, slug: 'mountain-strawberries',
    cat: 'fruits', subcat: 'Berries',
    title: 'Mountain Strawberries',
    subtitle: 'Tiny, fragrant, forest-edge',
    price: 4.99, old: 6.50, weight: '250 g',
    origin: 'Asheville, North Carolina',
    farmer: 'Piedmont Berry Co.',
    farmerSince: 'since 2011',
    farmerQuote: 'If they travel more than a hundred miles, they don\'t taste like strawberries anymore.',
    tags: ['Small-batch', 'Hand-picked'],
    img: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=1600&q=90&auto=format&fit=crop',
    description: 'Tiny fragrant strawberries grown at the edge of the Blue Ridge. Intensely floral, gone in a blink.',
    story: 'Grown at the tree-line where cool nights concentrate the sugar. Picked by hand in the morning.',
    keeps: '3 days, chilled',
    stock: 14, rating: 4.9, reviews: 221,
    featured: false, season: 'spring',
  },
  {
    id: 9, slug: 'butter-croissants',
    cat: 'bakery', subcat: 'Viennoiserie',
    title: 'Butter Croissants',
    subtitle: 'Laminated in cultured Normandy butter',
    price: 5.60, old: null, weight: 'Pack of 4',
    origin: 'Portland, Maine',
    farmer: 'Tiny Atlas Bakery',
    farmerSince: 'since 2017',
    farmerQuote: 'Butter, and patience. Mostly patience.',
    tags: ['Laminated by hand', 'Cultured butter'],
    img: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=1600&q=90&auto=format&fit=crop',
    description: 'Hand-laminated croissants folded with cultured Normandy butter. Baked Friday, shipped Friday, in your hands Saturday.',
    story: 'Laminated over two days in a small Portland shop. You can see every layer when you tear one in half.',
    keeps: 'Best day of; reheat in a low oven.',
    stock: 18, rating: 4.9, reviews: 184,
    featured: false, season: 'all',
  },
  {
    id: 10, slug: 'rainbow-bell-peppers',
    cat: 'vegetables', subcat: 'Fresh',
    title: 'Rainbow Bell Peppers',
    subtitle: 'Three colours, one grower',
    price: 3.80, old: null, weight: '3 pieces',
    origin: 'Hudson Valley, New York',
    farmer: 'Two Bridges Farm',
    farmerSince: 'since 2006',
    farmerQuote: 'We let them change colour on the vine. Patience, again.',
    tags: ['Greenhouse-ripened'],
    img: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=90&auto=format&fit=crop',
    description: 'Red, yellow, and orange bell peppers, all ripened on the vine rather than picked green and gassed.',
    story: 'Grown in unheated tunnels that let the fruit ripen slowly through September.',
    keeps: '1 week, chilled',
    stock: 32, rating: 4.7, reviews: 112,
    featured: false, season: 'autumn',
  },
  {
    id: 11, slug: 'farmhouse-cheddar',
    cat: 'dairy', subcat: 'Cheese',
    title: 'Aged Farmhouse Cheddar',
    subtitle: 'Eighteen months on wood',
    price: 8.90, old: null, weight: '250 g block',
    origin: 'Cabot, Vermont',
    farmer: 'Slow Hollow Creamery',
    farmerSince: 'since 1994',
    farmerQuote: 'Cheddar is a conversation between the cow, the milk, and time.',
    tags: ['Raw milk', 'Aged 18 months'],
    img: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=1600&q=90&auto=format&fit=crop',
    description: 'Raw-milk cheddar aged eighteen months on wooden planks. Crystalline, sharp, and built for a serious sandwich.',
    story: 'Made with raw milk from a neighbouring farm and aged on hemlock shelves. A small wheel a day, no more.',
    keeps: '4 weeks, chilled',
    stock: 16, rating: 4.9, reviews: 63,
    featured: false, season: 'all',
  },
  {
    id: 12, slug: 'valencia-oranges',
    cat: 'fruits', subcat: 'Citrus',
    title: 'Valencia Juicing Oranges',
    subtitle: 'Thin-skinned, ripe on the tree',
    price: 5.80, old: 7.20, weight: '1.5 kg',
    origin: 'Ventura County, California',
    farmer: 'Cielo Ranch',
    farmerSince: 'since 1989',
    farmerQuote: 'If we pick green to ship well, we\'re just selling carriage, not fruit.',
    tags: ['Tree-ripened', 'Low-spray'],
    img: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=1600&q=90&auto=format&fit=crop',
    description: 'Thin-skinned Valencias that are ripe when you open the box. For juice, not for the bowl.',
    story: 'Picked when the sugars hit twelve Brix and shipped inside seventy-two hours.',
    keeps: '2 weeks, cool pantry',
    stock: 22, rating: 4.7, reviews: 144,
    featured: false, season: 'winter',
  },
  {
    id: 13, slug: 'raw-wildflower-honey',
    cat: 'pantry', subcat: 'Apiary',
    title: 'Raw Wildflower Honey',
    subtitle: 'Hand-extracted, unfiltered',
    price: 14.50, old: null, weight: '500 g jar',
    origin: 'Northern Vermont',
    farmer: 'Gibson Apiary',
    farmerSince: 'since 2003',
    farmerQuote: 'Every jar tastes of wherever the bees were that week.',
    tags: ['Raw', 'Single origin'],
    img: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1600&q=90&auto=format&fit=crop',
    description: 'Unfiltered, unpasteurised wildflower honey from a small northern Vermont apiary. Crystallises after a month — warm gently.',
    story: 'Bill Gibson keeps forty hives on a buckwheat meadow. He extracts a few dozen jars at a time, by hand.',
    keeps: 'Indefinitely, sealed',
    stock: 40, rating: 4.9, reviews: 156,
    featured: true, season: 'all',
  },
  {
    id: 14, slug: 'cold-pressed-olive-oil',
    cat: 'pantry', subcat: 'Oils',
    title: 'Cold-pressed Olive Oil',
    subtitle: 'Single-estate Tuscan, late-harvest',
    price: 24.00, old: null, weight: '500 ml tin',
    origin: 'Toscana, Italy',
    farmer: 'Podere Vecchio',
    farmerSince: 'since 1962',
    farmerQuote: 'The mill runs four hours a day in November. That\'s our season.',
    tags: ['Single estate', 'Cold pressed'],
    img: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=1600&q=90&auto=format&fit=crop',
    description: 'A single-estate Tuscan olive oil, cold-pressed within four hours of picking. Peppery, green, and alive.',
    story: 'Podere Vecchio presses only one hundred tins a year. We take half of them.',
    keeps: '18 months, cool and dark',
    stock: 28, rating: 4.8, reviews: 92,
    featured: true, season: 'all',
  },
  {
    id: 15, slug: 'granola-nuts-berries',
    cat: 'pantry', subcat: 'Breakfast',
    title: 'Granola with Nuts & Berries',
    subtitle: 'Oven-baked in small trays',
    price: 8.40, old: null, weight: '350 g bag',
    origin: 'Burlington, Vermont',
    farmer: 'GreenKart Kitchen',
    farmerSince: 'since 2024',
    farmerQuote: 'Oats, maple, patience. Same as the bread.',
    tags: ['Small-batch', 'Low-sugar'],
    img: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1600&q=90&auto=format&fit=crop',
    description: 'Our own house granola — rolled oats, Vermont maple, pecans, dried blueberries, and a pinch of sea salt. Low sugar, high satisfaction.',
    story: 'We bake it in our small kitchen three mornings a week. The recipe hasn\'t changed since we started.',
    keeps: '6 weeks, sealed',
    stock: 60, rating: 4.7, reviews: 58,
    featured: false, season: 'all',
  },
  {
    id: 16, slug: 'ceremonial-matcha',
    cat: 'pantry', subcat: 'Tea',
    title: 'Ceremonial-grade Matcha',
    subtitle: 'First harvest, stone-ground',
    price: 28.00, old: 34.00, weight: '40 g tin',
    origin: 'Uji, Japan',
    farmer: 'Marufuku Tea Fields',
    farmerSince: 'since 1871',
    farmerQuote: 'The first harvest of spring — nothing else will do for tea.',
    tags: ['First harvest', 'Stone-ground'],
    img: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=1600&q=90&auto=format&fit=crop',
    description: 'A ceremonial-grade matcha from a seventh-generation family field in Uji. Bright, vegetal, almost sweet.',
    story: 'Shade-grown for three weeks, hand-picked, steamed, dried, and stone-ground at eighty revolutions a minute.',
    keeps: '6 months, refrigerated once opened',
    stock: 18, rating: 4.9, reviews: 78,
    featured: true, season: 'all',
  },
  {
    id: 17, slug: 'organic-almonds',
    cat: 'pantry', subcat: 'Nuts',
    title: 'Organic Raw Almonds',
    subtitle: 'Single-orchard, California',
    price: 11.60, old: null, weight: '300 g bag',
    origin: 'Capay Valley, California',
    farmer: 'Capay Organic',
    farmerSince: 'since 1989',
    farmerQuote: 'Almonds are a desert crop. Drip-irrigated and honest.',
    tags: ['Certified organic', 'Single orchard'],
    img: 'https://images.unsplash.com/photo-1574493582880-36b22d2c1ef2?w=1600&q=90&auto=format&fit=crop',
    description: 'Unpasteurised raw almonds from a single orchard in the Capay Valley. Sweet, milky, and worth the wait.',
    story: 'Harvested in September and shipped direct to us. Nothing sits in a warehouse.',
    keeps: '3 months, cool',
    stock: 44, rating: 4.6, reviews: 42,
    featured: false, season: 'autumn',
  },
  {
    id: 18, slug: 'spring-harvest-box',
    cat: 'pantry', subcat: 'Boxes',
    title: 'The Spring Harvest Box',
    subtitle: 'Volume Twelve — April',
    price: 48.00, old: null, weight: '≈ 5 kg, 9 varieties',
    origin: 'Mixed — Vermont & Hudson Valley',
    farmer: 'A dozen GreenKart farms',
    farmerSince: '',
    farmerQuote: 'One box a month, the first Saturday of the season.',
    tags: ['Subscription-ready', 'Pause anytime'],
    img: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?w=1600&q=90&auto=format&fit=crop',
    description: 'A month\'s worth of vegetables, fruit, and pantry staples — curated by what\'s in season within two hundred miles. Arrives in a single compostable crate.',
    story: 'Nine varieties, selected by the farmers themselves on the morning of shipping. Different every month.',
    keeps: 'See individual items',
    stock: 30, rating: 4.9, reviews: 421,
    featured: true, season: 'spring',
  },
  {
    id: 19, slug: 'wild-garlic-pesto',
    cat: 'pantry', subcat: 'Preserves',
    title: 'Wild Garlic Pesto',
    subtitle: 'Foraged in Vermont, made weekly',
    price: 9.80, old: null, weight: '180 g jar',
    origin: 'Windham County, Vermont',
    farmer: 'The Forager Kitchen',
    farmerSince: 'since 2019',
    farmerQuote: 'Two weeks a year, the woods give us garlic. We chase it.',
    tags: ['Foraged', 'Small-batch'],
    img: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1600&q=90&auto=format&fit=crop',
    description: 'Wild ramp pesto made in small batches during a narrow two-week window every April.',
    story: 'Foraged under licence in managed woodlands. What doesn\'t get jarred becomes next year\'s seed.',
    keeps: '4 weeks, chilled',
    stock: 22, rating: 4.8, reviews: 36,
    featured: false, season: 'spring',
  },
  {
    id: 20, slug: 'seeded-rye-crackers',
    cat: 'bakery', subcat: 'Crackers',
    title: 'Seeded Rye Crackers',
    subtitle: 'Four seeds, twice-baked',
    price: 6.80, old: null, weight: '220 g box',
    origin: 'Brooklyn, New York',
    farmer: 'Mill Street Bakery',
    farmerSince: 'since 2018',
    farmerQuote: 'Thin, brittle, and built for a serious cheese.',
    tags: ['Whole grain', 'Twice-baked'],
    img: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=1600&q=90&auto=format&fit=crop',
    description: 'Thin rye crackers with sunflower, pumpkin, flax, and sesame. Built for a serious cheese board.',
    story: 'Made from the bakery\'s weekly sourdough trim — nothing goes to waste.',
    keeps: '8 weeks, sealed',
    stock: 54, rating: 4.7, reviews: 128,
    featured: false, season: 'all',
  },
];

window.CATEGORIES = [
  { key: 'all',        label: 'Everything' },
  { key: 'fruits',     label: 'Fruits' },
  { key: 'vegetables', label: 'Vegetables' },
  { key: 'bakery',     label: 'Bakery' },
  { key: 'dairy',      label: 'Dairy & Eggs' },
  { key: 'pantry',     label: 'Pantry' },
];

window.JOURNAL = [
  { id: 'p1', slug: 'spring-asparagus-science',
    title: 'Why spring asparagus tastes sweeter than summer\'s.',
    excerpt: 'The field physics of sugar accumulation in the first warm week of April — and why your local farm stand has the timing right.',
    date: '2026-04-12', read: 6, author: 'Naomi Hart', category: 'Seasonal',
    img: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1600&q=90&auto=format&fit=crop',
    body: [
      'Asparagus is a strange plant. It stands up out of the ground one week every April and, for a few days, is the most delicious thing in the garden.',
      'The reason has to do with how sugars accumulate in the plant\'s crown through winter. By the time the first warm week arrives, the fern is ready to push a spear — and that spear is made almost entirely of stored starch, converting to sugar as it climbs.',
      'A summer spear, by contrast, has already fed a dozen ferns. It\'s structural cellulose and mild. Edible, but not memorable.',
      'The practical takeaway: if you can, eat asparagus in the first two weeks of its local season. The difference is not subtle.',
    ],
  },
  { id: 'p2', slug: 'ortega-family-farm',
    title: 'Four generations in one valley: the Ortega family farm.',
    excerpt: 'How seventy years of soil amendment make a courgette that hums when tapped — and why the family still argues about fertiliser at dinner.',
    date: '2026-04-05', read: 9, author: 'Paul Mensah', category: 'Farm life',
    img: 'https://images.unsplash.com/photo-1615485290398-15efa7a7a4ad?w=1600&q=90&auto=format&fit=crop',
    body: [
      'The Ortega farm sits in a crease between two hills that the Mission Blue butterfly also happens to favour.',
      'Ana\'s grandfather first planted there in 1953, on land that had been considered too rocky to be useful. The family took their first certified-organic crop to market in 1984.',
      'What makes their produce peculiar — a word Ana uses with obvious affection — is a soil amendment programme that has been refined over seventy years of trial, argument, and the occasional shouting match at the dinner table.',
    ],
  },
  { id: 'p3', slug: 'weeknight-spring-dinners',
    title: 'Five weeknight dinners from the spring box.',
    excerpt: 'Ways to turn Wednesday\'s delivery into Sunday\'s regret at having eaten it all. Recipes from our test kitchen.',
    date: '2026-03-28', read: 4, author: 'Lila Song', category: 'Recipes',
    img: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1600&q=90&auto=format&fit=crop',
    body: [
      'A spring box arrives Wednesday. A family dinner happens most Wednesdays. Here are five meals we default to when the box is still heavy.',
      'One: roasted asparagus with a poached egg and brown butter. Two: pea, mint, and ricotta toast. Three: radishes with good butter and flaky salt. Four: sorrel soup with a spoon of crème fraîche. Five: bibb lettuces with mustard vinaigrette and toasted seeds.',
      'Total cook time, all five: under two hours. Fresh produce wants minimal cooking; the ingredients do most of the work.',
    ],
  },
  { id: 'p4', slug: 'returnable-glass-bottle',
    title: 'The case for returnable glass.',
    excerpt: 'Why our milk still comes in a heavy bottle with a dollar deposit, and what we learned from the dairy who does the washing.',
    date: '2026-03-20', read: 7, author: 'Kimberly Okorocha', category: 'Sustainability',
    img: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=1600&q=90&auto=format&fit=crop',
    body: [
      'The dairy washes five thousand bottles a week. Each one makes about eighteen trips before being recycled.',
      'Counted over a year, the embodied carbon of a reusable glass bottle beats plastic by a comfortable margin — but only if customers actually return them. Our return rate is currently 84%.',
      'That\'s why the deposit is a dollar, and the collection box is at the door. Small friction, big improvement.',
    ],
  },
];

window.FARMS = [
  { id: 'f1', name: 'Ortega Family Farm', location: 'Sonoma County, California',
    since: 1953, acres: 120, specialty: 'Heirloom tomatoes, squash, alliums',
    img: 'https://images.unsplash.com/photo-1615485290398-15efa7a7a4ad?w=1400&q=90&auto=format&fit=crop',
    text: 'Four generations on land no-one else wanted. Seventy years of soil amendment, refined at the dinner table.' },
  { id: 'f2', name: 'The Abernathy Family', location: 'Hardwick, Vermont',
    since: 1978, acres: 18, specialty: 'Wild-harvested berries',
    img: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=1400&q=90&auto=format&fit=crop',
    text: 'A small hillside, a clone of wild blueberries, and a family who picks them before the birds find them.' },
  { id: 'f3', name: 'Green Pastures Dairy', location: 'Middlebury, Vermont',
    since: 1964, acres: 200, specialty: 'Jersey milk, non-homogenised',
    img: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=1400&q=90&auto=format&fit=crop',
    text: 'Forty-eight cows, twice a day, on rotational grass — and a returnable glass bottle.' },
  { id: 'f4', name: 'Mill Street Bakery', location: 'Brooklyn, New York',
    since: 2018, acres: 0, specialty: 'Sourdough, rye crackers',
    img: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=1400&q=90&auto=format&fit=crop',
    text: 'A small basement bakery baking three days a week. Stone-milled flour, 36-hour cold ferment.' },
  { id: 'f5', name: 'Gibson Apiary', location: 'Northern Vermont',
    since: 2003, acres: 6, specialty: 'Raw wildflower honey',
    img: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1400&q=90&auto=format&fit=crop',
    text: 'Forty hives in a buckwheat meadow. Honey extracted by hand, a few dozen jars at a time.' },
  { id: 'f6', name: 'Cielo Ranch', location: 'Ventura County, California',
    since: 1989, acres: 85, specialty: 'Citrus — low-spray, tree-ripened',
    img: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=1400&q=90&auto=format&fit=crop',
    text: 'An orchard that waits for twelve Brix before picking, and ships within seventy-two hours.' },
];
